CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

GRANT ALL PRIVILEGES ON SCHEMA bronze TO airflow;
GRANT ALL PRIVILEGES ON SCHEMA silver TO airflow;
GRANT ALL PRIVILEGES ON SCHEMA gold TO airflow;