services:
  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: g09_airflow
    env_file: .env
    environment:
      - AIRFLOW_UID=${AIRFLOW_UID:-0}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AF_DB_USER}:${AF_DB_PASS}@airflow_db:5432/${AF_DB_NAME}
      - AIRFLOW__API__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL=10
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=10
      - SOURCE_DB_HOST=data_warehouse
    volumes:
      - type: bind
        source: ./dags
        target: /opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      airflow_db:
        condition: service_healthy
      data_warehouse:
        condition: service_healthy
    restart: "no"
    networks:
      - g09_network

  airflow_db:
    image: postgres:17-alpine
    container_name: g09_airflow_db
    environment:
      - POSTGRES_USER=${AF_DB_USER}
      - POSTGRES_PASSWORD=${AF_DB_PASS}
      - POSTGRES_DB=${AF_DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AF_DB_USER} -d ${AF_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: "no"
    networks:
      - g09_network

  data_warehouse:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    image: g09_data_warehouse:custom
    container_name: g09_data_warehouse
    environment:
      - POSTGRES_USER=${SOURCE_DB_USER}
      - POSTGRES_PASSWORD=${SOURCE_DB_PASS}
      - POSTGRES_DB=${SOURCE_DB_NAME}
    volumes:
      - data_warehouse_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SOURCE_DB_USER} -d ${SOURCE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "no"
    networks:
      - g09_network

  dashboard:
    build: ./dashboard
    container_name: g09_dashboard
    env_file: .env
    environment:
      - SOURCE_DB_HOST=data_warehouse
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard/app.py:/app/app.py
      - ./dashboard/db.py:/app/db.py
      - ./dashboard/pages:/app/pages
    depends_on:
      data_warehouse:
        condition: service_healthy
    restart: "no"
    networks:
      - g09_network

volumes:
  airflow_db_data:
  airflow_logs:
  airflow_plugins:
  data_warehouse_data:

networks:
  g09_network:
    name: g09_network
    driver: bridge
