FROM apache/airflow:3.1.5-python3.11

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY docker/init-airflow.sh /opt/airflow/init-airflow.sh

CMD ["bash", "/opt/airflow/init-airflow.sh"]
