version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: clima_db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clima

    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: clima_app

    depends_on:
      - db

    volumes:
      - ./app:/app

    command: python clima.py
    
#version: '3.8'

#services:
#  warehouse:
#    image: postgres:17-alpine
#    container_name: g03_warehouse
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin123
#      POSTGRES_DB: weather_data
#    ports:
#      - "5435:5432"
#    volumes:
#     - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  # =========================
  # POSTGRES AIRFLOW METADATA
  # =========================
#  airflow_db:
#    image: postgres:15-alpine
#    container_name: g03_airflow_db
#    environment:
#      POSTGRES_USER: airflow
#      POSTGRES_PASSWORD: airflow
#      POSTGRES_DB: airflow
#    ports:
#      - "5434:5432"

  # =========================
  # AIRFLOW
  # =========================
#  airflow:
#    image: apache/airflow:2.8.1
#    container_name: g03_airflow
#    depends_on:
#      - airflow_db
#      - warehouse
#    environment:
#      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
#    ports:
#      - "8081:8080"
#    volumes:
#      - ./dags:/opt/airflow/dags